### PR TITLE
Doc updates

### PR DESCRIPTION
**Pull request by wiverson**
## What kind of change does this PR introduce?

Adds a bunch of documentation, including Unity setup information. Moves a lot of the documentation from the index to sub-pages, making it easier to read and update.

No code changes, just a lot of Markdown. :)

Declaring victory for today, may have more edits later this week/month. If you want to grab these now go for it, I'll open up another PR as I go along if you want to merge these now.

### CODE REVIEW

**Comment by acupofjose** [comment]
Wow. You went all out. Geez. These are awesome @wiverson!

Thoughts on how we should/would duplicate these on the main `supabase-csharp` repo?

**Comment by wiverson** [comment]
Sigh, I think it's just a regular PR? I can go ahead and hit merge...?

**Comment by acupofjose** [comment]
Merge it my friend. LGTM

**Comment by wiverson** [comment]
Hahaha I put this all in the wrong repo. Sigh. Fixed and moved to the main repo. Was so busy writing Markdown I didn't pay attention.

**Pull request merged**
