### PR TITLE
Update usage of redirectTo to reflect gotrue-js usage

### LINKED ISSUE #29: SendMagicLinkEmail puts RedirectTo option in incorrect part of request
It seems like SendMagicLinkEmail appends RedirectTo to the POST body of the request, but it looks like the server expects it to be a query parameter. When a magic link is requested using this library using a redirect_to option, the magic link returned from the server ignores the option passed.

I spun up a Supabase instance here so I could dump the request data and used two client environments: a Flutter app which I know works, and a C# app which does not, both using the same API.

When requesting a magic link using the flutter library, it makes a request to the server like so:
`POST /auth/v1/magiclink?redirect_to=com.example.example%3A%2F%2Flogin-callback%2F HTTP/1.1" 200 2 "-" "Dart/2.16 (dart:io)`
with a POST body of:
`{\x22email\x22:\x22email@example.com\x22}`

Using this C# library, the request instead looks like this:
`POST /auth/v1/magiclink HTTP/1.1" 429 91 "-" "Dalvik/2.1.0 (Linux; U; Android 12; sdk_gphone64_x86_64 Build/SPB5.210812.003)`
with a POST body of:
`{\x22email\x22:\x22email@example.com\x22,\x22redirect_to\x22:\x22com.example.example://login-callback/\x22}`

### PR DESCRIPTION
**Pull request by RedChops**
Fixes #29 

I just saw your message, I already had this built up and testing it out, so you can feel free to use this!

### CODE REVIEW

**Comment by RedChops** [comment]
The only slightly dodgy thing here is that when the URI comes back in from the redirect, the query string part is actually a query string-encoded fragment. This affects the HttpUtility.ParseQueryString(uri.Query) call in GetSessionFromUrl, since uri.Query is null.

I worked around this by adjusting my call to 
`            var uri = new Uri(Intent.Data.ToString().Replace("#", "?"));
            client.GetSessionFromUrl(uri);`
but that's probably not ideal.

**Comment by acupofjose** [comment]
@RedChops I opened a separate PR to make changes, but saw that you actually let me commit onto yours directly (whoops).
Thanks for taking the time to open this, really nice to have your contribution!

I would rather use the built-in `UriBuilder` to handle adding the `redirect_to` into the `query`, so you'll see those changes there.
I also took your suggestion and adjusted the `client.GetSessionFromUrl()` (with a slight adjustment). 

Will you check those changes and see if they work well for you?

**Comment by RedChops** [comment]
Happy to help!

The updates look great, I prefer the UriBuilder as well. I loaded up the new version in my application and it works perfectly well

**Comment by acupofjose** [comment]
Awesome, I'll bundle a release and credit you in the CHANGELOG - let me know if you find anything else in the future!

**Pull request merged**
