### PR TITLE
Structure project to conform to DI with backwards compatibility.

### PR DESCRIPTION
**Pull request by acupofjose**
In reference to supabase-community/supabase-csharp#23
- BREAKING CHANGE: Almost all method signatures now return Interfaces
- Interfaces created for anything that was publicly accessible.
- Additional methods added that allow for generic types accepting interfaces, allowing for injection of types but defaulting to the shipped, concrete classes.

### CODE REVIEW

**Comment by HunteRoi** [comment]
Hello there! Sorry for the late comeback.

I have taken a look at your PR. Here are my comments on it:
- don't interface everything. Follow this simple rule: if there is some kind of logic, than interface is required. Otherwise, use the class.
- don't use generic methods directly in classes that implement an interfaces. Rather define generic methods in your interfaces and let the implementation only deal with specific behavior. Instead of 
```csharp
public interface IGotrueApi
{
    Task<T> CreateUser<T>(string jwt, IAdminUserAttributes attributes = null) where T : User;
     ....
}

public class Api : IGotrueApi
{
    public Task<T> CreateUser<T>(string jwt, IAdminUserAttributes attributes = null) where T : User
    {
        // code
    }
    
    public Task<User> CreateUser(string jwt, IAdminUserAttributes attributes = null) => CreateUser<User>(jwt, attributes);

     ....
}
```

go like this:

```csharp
public interface IGotrueApi<TUser, TUserList, TSession>
    where TUser : User
    where TUserList : UserList
    where TSession : Session
{
    Task<TUser> CreateUser(string jwt, AdminUserAttributes attributes = null);
    ...
}

public class Api : IGotrueApi<User, UserList, Session>
{
    public Task<User> CreateUser(string jwt, AdminUserAttributes attributes = null)
    {
        // code
    }
    
     ....
}
```

**Comment by acupofjose** [comment]
Thanks for the feedback! I'll adjust and come back with some changes - that makes a lot more sense to me!

**Comment by HunteRoi** [comment]
Any news on this @acupofjose ?

**Comment by acupofjose** [comment]
@HunteRoi  oop. To be honest, it's in exactly the same spot as I left it here. Thanks for the encouragement, needed a ping on it.

**Comment by acupofjose** [comment]
Closing in favor of #40 @HunteRoi

**Pull request closed without merging**
